# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawFundsClient, RawFundsClient


class FundsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFundsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFundsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFundsClient
        """
        return self._raw_client

    def search(
        self,
        *,
        vintage_year: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Search for venture capital and private equity funds by name. Returns matching fund profiles with size, vintage year, and investment focus. Use this to find fund entity IDs for detailed lookups.

        Parameters
        ----------
        vintage_year : typing.Optional[int]
            Filter by vintage year

        limit : typing.Optional[int]
            Maximum results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.funds.search()
        """
        _response = self._raw_client.search(vintage_year=vintage_year, limit=limit, request_options=request_options)
        return _response.data

    def bio(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get comprehensive fund profile including fund size, vintage year, investment strategy, stage focus, and sector focus. This is the primary endpoint for fund overview data.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.funds.bio(
            fund_id="sequoia",
        )
        """
        _response = self._raw_client.bio(fund_id, request_options=request_options)
        return _response.data

    def performance(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Coming Soon: Get fund performance metrics including IRR, TVPI, DPI, and RVPI. Will return LP-level performance data when implemented with proprietary fund reporting.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.funds.performance(
            fund_id="sequoia",
        )
        """
        _response = self._raw_client.performance(fund_id, request_options=request_options)
        return _response.data

    def active_investments(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get current portfolio companies invested by this specific fund. Returns company names, investment amounts, and current status.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.funds.active_investments(
            fund_id="sequoia",
        )
        """
        _response = self._raw_client.active_investments(fund_id, request_options=request_options)
        return _response.data

    def all_investments(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get complete investment history for this specific fund including current and exited positions. Returns all companies backed by the fund with outcomes.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.funds.all_investments(
            fund_id="sequoia",
        )
        """
        _response = self._raw_client.all_investments(fund_id, request_options=request_options)
        return _response.data

    def commitments(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get limited partner commitments to the fund including LP names and commitment amounts. Returns investor base and capital structure.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.funds.commitments(
            fund_id="sequoia",
        )
        """
        _response = self._raw_client.commitments(fund_id, request_options=request_options)
        return _response.data

    def cash_flows(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Coming Soon: Get fund cash flow history including capital calls and distributions. Will return quarterly cash flow statements when implemented with LP reporting data.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.funds.cash_flows(
            fund_id="sequoia",
        )
        """
        _response = self._raw_client.cash_flows(fund_id, request_options=request_options)
        return _response.data

    def benchmark(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Coming Soon: Get fund performance compared to industry benchmarks and peer funds. Will return quartile rankings and comparative metrics when implemented.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.funds.benchmark(
            fund_id="sequoia",
        )
        """
        _response = self._raw_client.benchmark(fund_id, request_options=request_options)
        return _response.data

    def people(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get investment team members for the fund including partners, principals, and associates. Returns names, titles, and LinkedIn profiles.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.funds.people(
            fund_id="sequoia",
        )
        """
        _response = self._raw_client.people(fund_id, request_options=request_options)
        return _response.data

    def preferences(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get investment criteria and preferences for the fund including stage focus, sector preferences, geography, and check size ranges.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.funds.preferences(
            fund_id="sequoia",
        )
        """
        _response = self._raw_client.preferences(fund_id, request_options=request_options)
        return _response.data

    def updates(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get changelog of updates to fund profile data. Returns history of changes including new investments, exits, and team changes with timestamps.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.funds.updates(
            fund_id="sequoia",
        )
        """
        _response = self._raw_client.updates(fund_id, request_options=request_options)
        return _response.data


class AsyncFundsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFundsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFundsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFundsClient
        """
        return self._raw_client

    async def search(
        self,
        *,
        vintage_year: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Search for venture capital and private equity funds by name. Returns matching fund profiles with size, vintage year, and investment focus. Use this to find fund entity IDs for detailed lookups.

        Parameters
        ----------
        vintage_year : typing.Optional[int]
            Filter by vintage year

        limit : typing.Optional[int]
            Maximum results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.funds.search()


        asyncio.run(main())
        """
        _response = await self._raw_client.search(
            vintage_year=vintage_year, limit=limit, request_options=request_options
        )
        return _response.data

    async def bio(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get comprehensive fund profile including fund size, vintage year, investment strategy, stage focus, and sector focus. This is the primary endpoint for fund overview data.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.funds.bio(
                fund_id="sequoia",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.bio(fund_id, request_options=request_options)
        return _response.data

    async def performance(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Coming Soon: Get fund performance metrics including IRR, TVPI, DPI, and RVPI. Will return LP-level performance data when implemented with proprietary fund reporting.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.funds.performance(
                fund_id="sequoia",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.performance(fund_id, request_options=request_options)
        return _response.data

    async def active_investments(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get current portfolio companies invested by this specific fund. Returns company names, investment amounts, and current status.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.funds.active_investments(
                fund_id="sequoia",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.active_investments(fund_id, request_options=request_options)
        return _response.data

    async def all_investments(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get complete investment history for this specific fund including current and exited positions. Returns all companies backed by the fund with outcomes.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.funds.all_investments(
                fund_id="sequoia",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.all_investments(fund_id, request_options=request_options)
        return _response.data

    async def commitments(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get limited partner commitments to the fund including LP names and commitment amounts. Returns investor base and capital structure.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.funds.commitments(
                fund_id="sequoia",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.commitments(fund_id, request_options=request_options)
        return _response.data

    async def cash_flows(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Coming Soon: Get fund cash flow history including capital calls and distributions. Will return quarterly cash flow statements when implemented with LP reporting data.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.funds.cash_flows(
                fund_id="sequoia",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cash_flows(fund_id, request_options=request_options)
        return _response.data

    async def benchmark(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Coming Soon: Get fund performance compared to industry benchmarks and peer funds. Will return quartile rankings and comparative metrics when implemented.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.funds.benchmark(
                fund_id="sequoia",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.benchmark(fund_id, request_options=request_options)
        return _response.data

    async def people(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get investment team members for the fund including partners, principals, and associates. Returns names, titles, and LinkedIn profiles.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.funds.people(
                fund_id="sequoia",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.people(fund_id, request_options=request_options)
        return _response.data

    async def preferences(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get investment criteria and preferences for the fund including stage focus, sector preferences, geography, and check size ranges.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.funds.preferences(
                fund_id="sequoia",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.preferences(fund_id, request_options=request_options)
        return _response.data

    async def updates(
        self, fund_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get changelog of updates to fund profile data. Returns history of changes including new investments, exits, and team changes with timestamps.

        Parameters
        ----------
        fund_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.funds.updates(
                fund_id="sequoia",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.updates(fund_id, request_options=request_options)
        return _response.data
