# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .index_azure_directory_request_v2processing_type import IndexAzureDirectoryRequestV2ProcessingType
    from .index_azure_file_request_v2processing_type import IndexAzureFileRequestV2ProcessingType
    from .index_azure_request_v2processing_type import IndexAzureRequestV2ProcessingType
    from .index_gcs_directory_request_v2processing_type import IndexGcsDirectoryRequestV2ProcessingType
    from .index_gcs_file_request_v2processing_type import IndexGcsFileRequestV2ProcessingType
    from .index_gcs_request_v2processing_type import IndexGcsRequestV2ProcessingType
    from .index_r2directory_request_v2jurisdiction import IndexR2DirectoryRequestV2Jurisdiction
    from .index_r2directory_request_v2processing_type import IndexR2DirectoryRequestV2ProcessingType
    from .index_r2file_request_v2jurisdiction import IndexR2FileRequestV2Jurisdiction
    from .index_r2file_request_v2processing_type import IndexR2FileRequestV2ProcessingType
    from .index_r2request_v2jurisdiction import IndexR2RequestV2Jurisdiction
    from .index_r2request_v2processing_type import IndexR2RequestV2ProcessingType
    from .index_s3directory_request_v2processing_type import IndexS3DirectoryRequestV2ProcessingType
    from .index_s3file_request_v2processing_type import IndexS3FileRequestV2ProcessingType
    from .index_s3request_v2processing_type import IndexS3RequestV2ProcessingType
    from .index_url_request_v2processing_type import IndexUrlRequestV2ProcessingType
_dynamic_imports: typing.Dict[str, str] = {
    "IndexAzureDirectoryRequestV2ProcessingType": ".index_azure_directory_request_v2processing_type",
    "IndexAzureFileRequestV2ProcessingType": ".index_azure_file_request_v2processing_type",
    "IndexAzureRequestV2ProcessingType": ".index_azure_request_v2processing_type",
    "IndexGcsDirectoryRequestV2ProcessingType": ".index_gcs_directory_request_v2processing_type",
    "IndexGcsFileRequestV2ProcessingType": ".index_gcs_file_request_v2processing_type",
    "IndexGcsRequestV2ProcessingType": ".index_gcs_request_v2processing_type",
    "IndexR2DirectoryRequestV2Jurisdiction": ".index_r2directory_request_v2jurisdiction",
    "IndexR2DirectoryRequestV2ProcessingType": ".index_r2directory_request_v2processing_type",
    "IndexR2FileRequestV2Jurisdiction": ".index_r2file_request_v2jurisdiction",
    "IndexR2FileRequestV2ProcessingType": ".index_r2file_request_v2processing_type",
    "IndexR2RequestV2Jurisdiction": ".index_r2request_v2jurisdiction",
    "IndexR2RequestV2ProcessingType": ".index_r2request_v2processing_type",
    "IndexS3DirectoryRequestV2ProcessingType": ".index_s3directory_request_v2processing_type",
    "IndexS3FileRequestV2ProcessingType": ".index_s3file_request_v2processing_type",
    "IndexS3RequestV2ProcessingType": ".index_s3request_v2processing_type",
    "IndexUrlRequestV2ProcessingType": ".index_url_request_v2processing_type",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "IndexAzureDirectoryRequestV2ProcessingType",
    "IndexAzureFileRequestV2ProcessingType",
    "IndexAzureRequestV2ProcessingType",
    "IndexGcsDirectoryRequestV2ProcessingType",
    "IndexGcsFileRequestV2ProcessingType",
    "IndexGcsRequestV2ProcessingType",
    "IndexR2DirectoryRequestV2Jurisdiction",
    "IndexR2DirectoryRequestV2ProcessingType",
    "IndexR2FileRequestV2Jurisdiction",
    "IndexR2FileRequestV2ProcessingType",
    "IndexR2RequestV2Jurisdiction",
    "IndexR2RequestV2ProcessingType",
    "IndexS3DirectoryRequestV2ProcessingType",
    "IndexS3FileRequestV2ProcessingType",
    "IndexS3RequestV2ProcessingType",
    "IndexUrlRequestV2ProcessingType",
]
