# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.job_cancel_response_v2 import JobCancelResponseV2
from ..types.job_status_response_v2 import JobStatusResponseV2
from .raw_client import AsyncRawJobsClient, RawJobsClient


class JobsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawJobsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawJobsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawJobsClient
        """
        return self._raw_client

    def get_job_status_v2(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> JobStatusResponseV2:
        """
        Get the status of an indexing job with detailed progress information.

        ## Status Values
        - **pending**: Job created but processing hasn't started yet
        - **running**: Job is actively processing files
        - **completed**: Job finished successfully
        - **failed**: Job encountered an error
        - **cancelled**: Job was cancelled by user

        ## Processing Stages
        When status is `running`, the `progress.current_stage` field indicates which stage:
        1. **scanning**: Scanning bucket for files
        2. **extracting**: Extracting text content from documents
        3. **chunking**: Splitting documents into semantic chunks
        4. **tagging**: AI tagging and summarization
        5. **embedding**: Generating vector embeddings
        6. **finalizing**: Aggregating results and recording billing

        ## File Status Values
        Each file in the `files` array has a status:
        - **queued**: Waiting to be processed
        - **processing**: Currently being processed
        - **completed**: Successfully indexed
        - **failed**: Failed to process (see error_code/error_message)
        - **skipped**: Skipped (already indexed, unsupported type, etc.)
        - **cancelled**: Processing was cancelled

        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobStatusResponseV2
            Job Status

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.jobs.get_job_status_v2(
            job_id="job_s3_abc123",
        )
        """
        _response = self._raw_client.get_job_status_v2(job_id, request_options=request_options)
        return _response.data

    def cancel_job_v2(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> JobCancelResponseV2:
        """
        Cancel an indexing job.

        Behavior:
        - If job is pending or running -> transitions to cancelled
        - If job is already completed/failed/cancelled -> returns 200 with current state (idempotent)

        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobCancelResponseV2
            Cancel Result

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.jobs.cancel_job_v2(
            job_id="job_s3_abc123",
        )
        """
        _response = self._raw_client.cancel_job_v2(job_id, request_options=request_options)
        return _response.data


class AsyncJobsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawJobsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawJobsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawJobsClient
        """
        return self._raw_client

    async def get_job_status_v2(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> JobStatusResponseV2:
        """
        Get the status of an indexing job with detailed progress information.

        ## Status Values
        - **pending**: Job created but processing hasn't started yet
        - **running**: Job is actively processing files
        - **completed**: Job finished successfully
        - **failed**: Job encountered an error
        - **cancelled**: Job was cancelled by user

        ## Processing Stages
        When status is `running`, the `progress.current_stage` field indicates which stage:
        1. **scanning**: Scanning bucket for files
        2. **extracting**: Extracting text content from documents
        3. **chunking**: Splitting documents into semantic chunks
        4. **tagging**: AI tagging and summarization
        5. **embedding**: Generating vector embeddings
        6. **finalizing**: Aggregating results and recording billing

        ## File Status Values
        Each file in the `files` array has a status:
        - **queued**: Waiting to be processed
        - **processing**: Currently being processed
        - **completed**: Successfully indexed
        - **failed**: Failed to process (see error_code/error_message)
        - **skipped**: Skipped (already indexed, unsupported type, etc.)
        - **cancelled**: Processing was cancelled

        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobStatusResponseV2
            Job Status

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.jobs.get_job_status_v2(
                job_id="job_s3_abc123",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_job_status_v2(job_id, request_options=request_options)
        return _response.data

    async def cancel_job_v2(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> JobCancelResponseV2:
        """
        Cancel an indexing job.

        Behavior:
        - If job is pending or running -> transitions to cancelled
        - If job is already completed/failed/cancelled -> returns 200 with current state (idempotent)

        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobCancelResponseV2
            Cancel Result

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.jobs.cancel_job_v2(
                job_id="job_s3_abc123",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel_job_v2(job_id, request_options=request_options)
        return _response.data
