# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class BillingCredits(UniversalBaseModel):
    """
    Credit usage for a completed job
    """

    used: float = pydantic.Field()
    """
    Credits consumed by this job (1 per basic page, 2.5 per advanced page)
    """

    remaining: float = pydantic.Field()
    """
    Credits remaining in your current billing period
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
