# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class RelevantDocumentV2(UniversalBaseModel):
    """
    A relevant document returned for inference=true queries
    """

    relevancy_score: typing.Optional[float] = pydantic.Field(default=None)
    """
    Relevancy score from 0 to 1
    """

    document_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the document
    """

    filename: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the document file
    """

    excerpt: typing.Optional[str] = pydantic.Field(default=None)
    """
    Relevant excerpt from the document
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
