# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .credit_analysis_bdc_search_request_seniority import CreditAnalysisBdcSearchRequestSeniority
    from .credit_analysis_funds_search_request_strategy import CreditAnalysisFundsSearchRequestStrategy
    from .credit_analysis_news_bulk_response import CreditAnalysisNewsBulkResponse
    from .credit_analysis_news_bulk_response_results_item import CreditAnalysisNewsBulkResponseResultsItem
    from .credit_analysis_news_detail_response import CreditAnalysisNewsDetailResponse
    from .credit_analysis_news_recent_response import CreditAnalysisNewsRecentResponse
    from .credit_analysis_news_recent_response_results_item import CreditAnalysisNewsRecentResponseResultsItem
    from .credit_analysis_news_search_response import CreditAnalysisNewsSearchResponse
    from .credit_analysis_news_search_response_results_item import CreditAnalysisNewsSearchResponseResultsItem
    from .credit_analysis_sba_search_request_status import CreditAnalysisSbaSearchRequestStatus
_dynamic_imports: typing.Dict[str, str] = {
    "CreditAnalysisBdcSearchRequestSeniority": ".credit_analysis_bdc_search_request_seniority",
    "CreditAnalysisFundsSearchRequestStrategy": ".credit_analysis_funds_search_request_strategy",
    "CreditAnalysisNewsBulkResponse": ".credit_analysis_news_bulk_response",
    "CreditAnalysisNewsBulkResponseResultsItem": ".credit_analysis_news_bulk_response_results_item",
    "CreditAnalysisNewsDetailResponse": ".credit_analysis_news_detail_response",
    "CreditAnalysisNewsRecentResponse": ".credit_analysis_news_recent_response",
    "CreditAnalysisNewsRecentResponseResultsItem": ".credit_analysis_news_recent_response_results_item",
    "CreditAnalysisNewsSearchResponse": ".credit_analysis_news_search_response",
    "CreditAnalysisNewsSearchResponseResultsItem": ".credit_analysis_news_search_response_results_item",
    "CreditAnalysisSbaSearchRequestStatus": ".credit_analysis_sba_search_request_status",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreditAnalysisBdcSearchRequestSeniority",
    "CreditAnalysisFundsSearchRequestStrategy",
    "CreditAnalysisNewsBulkResponse",
    "CreditAnalysisNewsBulkResponseResultsItem",
    "CreditAnalysisNewsDetailResponse",
    "CreditAnalysisNewsRecentResponse",
    "CreditAnalysisNewsRecentResponseResultsItem",
    "CreditAnalysisNewsSearchResponse",
    "CreditAnalysisNewsSearchResponseResultsItem",
    "CreditAnalysisSbaSearchRequestStatus",
]
