# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .credit_analysis_news_bulk_response_results_item import CreditAnalysisNewsBulkResponseResultsItem


class CreditAnalysisNewsBulkResponse(UniversalBaseModel):
    results: typing.Optional[typing.List[CreditAnalysisNewsBulkResponseResultsItem]] = None
    total_queries: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of queries processed
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
