# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .credit_analysis_news_search_response_results_item import CreditAnalysisNewsSearchResponseResultsItem


class CreditAnalysisNewsSearchResponse(UniversalBaseModel):
    query: typing.Optional[str] = pydantic.Field(default=None)
    """
    Search query
    """

    results: typing.Optional[typing.List[CreditAnalysisNewsSearchResponseResultsItem]] = None
    total_results: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total matching results
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Results limit
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
