# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InvestorsBioResponseInvestorType(UniversalBaseModel):
    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Investor type (vc, pe, angel, corporate)
    """

    stage_focus: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Stage focus areas
    """

    sector_focus: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Sector focus areas
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
