# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .investors_funds_response_funds_item import InvestorsFundsResponseFundsItem


class InvestorsFundsResponse(UniversalBaseModel):
    investor_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Investor entity ID
    """

    investor_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Investor name
    """

    funds: typing.Optional[typing.List[InvestorsFundsResponseFundsItem]] = None
    total_funds: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of funds
    """

    total_aum: typing.Optional[float] = pydantic.Field(default=None)
    """
    Total assets under management
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
