# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InvestorsFundsResponseFundsItem(UniversalBaseModel):
    fund_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Fund name
    """

    fund_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Fund entity ID
    """

    fund_size: typing.Optional[float] = pydantic.Field(default=None)
    """
    Fund size in USD
    """

    vintage_year: typing.Optional[int] = pydantic.Field(default=None)
    """
    Vintage year
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Fund status
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
