# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class InvestorsBoardSeatsResponseBoardSeatsItem(UniversalBaseModel):
    company_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Company name
    """

    company_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Company entity ID
    """

    board_member: typing.Optional[str] = pydantic.Field(default=None)
    """
    Board member name
    """

    role: typing.Optional[str] = pydantic.Field(default=None)
    """
    Board role
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
