# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PatentsSearchResponsePatentsItem(UniversalBaseModel):
    patent_id: typing.Optional[str] = None
    title: typing.Optional[str] = None
    abstract: typing.Optional[str] = None
    filing_date: typing.Optional[str] = None
    grant_date: typing.Optional[str] = None
    assignee: typing.Optional[str] = None
    patent_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    Patent number (e.g. US11475380B2)
    """

    publication_date: typing.Optional[str] = pydantic.Field(default=None)
    """
    Publication date
    """

    inventors: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Inventor names
    """

    patent_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Google Patents URL
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
