# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PeopleBioResponseCurrentCompany(UniversalBaseModel):
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Company name
    """

    title: typing.Optional[str] = pydantic.Field(default=None)
    """
    Job title
    """

    start_date: typing.Optional[str] = pydantic.Field(default=None)
    """
    Start date
    """

    company_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Company entity ID
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
