# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..types.query_response_v2 import QueryResponseV2

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawQueryClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def collection_v2(
        self,
        collection_name: str,
        *,
        query: str,
        inference: typing.Optional[bool] = OMIT,
        stream: typing.Optional[bool] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        rerank: typing.Optional[bool] = OMIT,
        metadata_filter: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        custom_prompt: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[QueryResponseV2]:
        """
        Execute a natural language query against a collection.

        When `inference=true`, returns an AI-generated response with relevant documents.
        When `inference=false`, returns raw search results with content and metadata.

        ## Streaming (SSE)

        When `stream: true` and `inference: true`, the response is a Server-Sent Events stream. Every `data:` field is a JSON object with a `type` discriminator.

        ### SSE Event Types

        | `type` value | Schema | Description |
        |---|---|---|
        | `text.delta` | `QueryStreamTextEvent` | Incremental text chunk of the AI response. |
        | `tool.start` | `QueryStreamToolStartEvent` | The agent is performing a knowledge-base search. |
        | `tool.end` | `QueryStreamToolEndEvent` | A tool call completed. `tool_call_id` correlates with the preceding `tool.start`. |
        | `stream_complete` | `QueryStreamCompleteEvent` | Stream finished successfully. Close the connection. |
        | `stream_error` | `QueryStreamErrorEvent` | An error occurred. Close the connection. |

        ### Example SSE Stream

        ```
        data: {"type":"tool.start","seq":1,"run_id":"run_abc","tool_call_id":"tc_1","name":"searchKnowledgeBase","args":{"query":"revenue projections Q4"}}

        data: {"type":"tool.end","seq":2,"run_id":"run_abc","tool_call_id":"tc_1","name":"searchKnowledgeBase","ok":true,"result_summary":{"resultCount":12}}

        data: {"type":"text.delta","seq":3,"run_id":"run_abc","data":"Based on the documents"}
        data: {"type":"text.delta","seq":4,"run_id":"run_abc","data":" provided, the revenue"}
        data: {"type":"text.delta","seq":5,"run_id":"run_abc","data":" projections for Q4 show"}
        data: {"type":"text.delta","seq":6,"run_id":"run_abc","data":" a 15% increase over Q3."}

        data: {"type":"stream_complete","metadata":{"totalResults":12,"totalSearches":1},"stats":{"totalTokens":150}}
        ```

        ### Notes

        - The agent may perform multiple searches per query. Each search produces a `tool.start` / `tool.end` pair.
        - Text chunks are interleaved between tool events — text arrives after the agent has gathered results from a search.
        - Connect with `Accept: text/event-stream` and set a generous timeout (120s+) for long responses.

        Parameters
        ----------
        collection_name : str

        query : str
            The natural language query to search for

        inference : typing.Optional[bool]
            Enable LLM-generated answers based on the relevant sections retrieved. When false, returns raw search results.

        stream : typing.Optional[bool]
            Enable real-time streaming of the response

        top_k : typing.Optional[int]
            Number of results to return. Only valid when inference=false. Not supported when inference=true (the agent controls its own search strategy).

        rerank : typing.Optional[bool]
            Enable Voyage AI rerank-2.5 reranking for improved relevance ordering. Adds ~100-300ms latency.

        metadata_filter : typing.Optional[typing.Dict[str, typing.Any]]
            Filter expression for vector search. Supports: $eq, $ne, $gt, $gte, $lt, $lte, $in, $nin, $and, $or

        custom_prompt : typing.Optional[str]
            Custom system prompt to override the default RAG prompt when inference=true. Allows customizing how the LLM processes and responds to the query with the retrieved context.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[QueryResponseV2]
            Successful Response — returns JSON when `stream: false`, or SSE event stream when `stream: true`.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/collections/{jsonable_encoder(collection_name)}/query",
            method="POST",
            json={
                "query": query,
                "inference": inference,
                "stream": stream,
                "top_k": top_k,
                "rerank": rerank,
                "metadata_filter": metadata_filter,
                "custom_prompt": custom_prompt,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    QueryResponseV2,
                    parse_obj_as(
                        type_=QueryResponseV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawQueryClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def collection_v2(
        self,
        collection_name: str,
        *,
        query: str,
        inference: typing.Optional[bool] = OMIT,
        stream: typing.Optional[bool] = OMIT,
        top_k: typing.Optional[int] = OMIT,
        rerank: typing.Optional[bool] = OMIT,
        metadata_filter: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        custom_prompt: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[QueryResponseV2]:
        """
        Execute a natural language query against a collection.

        When `inference=true`, returns an AI-generated response with relevant documents.
        When `inference=false`, returns raw search results with content and metadata.

        ## Streaming (SSE)

        When `stream: true` and `inference: true`, the response is a Server-Sent Events stream. Every `data:` field is a JSON object with a `type` discriminator.

        ### SSE Event Types

        | `type` value | Schema | Description |
        |---|---|---|
        | `text.delta` | `QueryStreamTextEvent` | Incremental text chunk of the AI response. |
        | `tool.start` | `QueryStreamToolStartEvent` | The agent is performing a knowledge-base search. |
        | `tool.end` | `QueryStreamToolEndEvent` | A tool call completed. `tool_call_id` correlates with the preceding `tool.start`. |
        | `stream_complete` | `QueryStreamCompleteEvent` | Stream finished successfully. Close the connection. |
        | `stream_error` | `QueryStreamErrorEvent` | An error occurred. Close the connection. |

        ### Example SSE Stream

        ```
        data: {"type":"tool.start","seq":1,"run_id":"run_abc","tool_call_id":"tc_1","name":"searchKnowledgeBase","args":{"query":"revenue projections Q4"}}

        data: {"type":"tool.end","seq":2,"run_id":"run_abc","tool_call_id":"tc_1","name":"searchKnowledgeBase","ok":true,"result_summary":{"resultCount":12}}

        data: {"type":"text.delta","seq":3,"run_id":"run_abc","data":"Based on the documents"}
        data: {"type":"text.delta","seq":4,"run_id":"run_abc","data":" provided, the revenue"}
        data: {"type":"text.delta","seq":5,"run_id":"run_abc","data":" projections for Q4 show"}
        data: {"type":"text.delta","seq":6,"run_id":"run_abc","data":" a 15% increase over Q3."}

        data: {"type":"stream_complete","metadata":{"totalResults":12,"totalSearches":1},"stats":{"totalTokens":150}}
        ```

        ### Notes

        - The agent may perform multiple searches per query. Each search produces a `tool.start` / `tool.end` pair.
        - Text chunks are interleaved between tool events — text arrives after the agent has gathered results from a search.
        - Connect with `Accept: text/event-stream` and set a generous timeout (120s+) for long responses.

        Parameters
        ----------
        collection_name : str

        query : str
            The natural language query to search for

        inference : typing.Optional[bool]
            Enable LLM-generated answers based on the relevant sections retrieved. When false, returns raw search results.

        stream : typing.Optional[bool]
            Enable real-time streaming of the response

        top_k : typing.Optional[int]
            Number of results to return. Only valid when inference=false. Not supported when inference=true (the agent controls its own search strategy).

        rerank : typing.Optional[bool]
            Enable Voyage AI rerank-2.5 reranking for improved relevance ordering. Adds ~100-300ms latency.

        metadata_filter : typing.Optional[typing.Dict[str, typing.Any]]
            Filter expression for vector search. Supports: $eq, $ne, $gt, $gte, $lt, $lte, $in, $nin, $and, $or

        custom_prompt : typing.Optional[str]
            Custom system prompt to override the default RAG prompt when inference=true. Allows customizing how the LLM processes and responds to the query with the retrieved context.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[QueryResponseV2]
            Successful Response — returns JSON when `stream: false`, or SSE event stream when `stream: true`.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/collections/{jsonable_encoder(collection_name)}/query",
            method="POST",
            json={
                "query": query,
                "inference": inference,
                "stream": stream,
                "top_k": top_k,
                "rerank": rerank,
                "metadata_filter": metadata_filter,
                "custom_prompt": custom_prompt,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    QueryResponseV2,
                    parse_obj_as(
                        type_=QueryResponseV2,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
