# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DealsStockInfoResponse(UniversalBaseModel):
    deal_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Deal identifier
    """

    company_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Company name
    """

    service_providers: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = None
    total: typing.Optional[int] = None
    data_sources: typing.Optional[typing.List[str]] = None
    search_results: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = pydantic.Field(default=None)
    """
    Stock/equity related search results
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
