# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DealsValuationResponseTerms(UniversalBaseModel):
    deal_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Deal type
    """

    amount: typing.Optional[float] = pydantic.Field(default=None)
    """
    Deal amount in USD
    """

    valuation_pre_money: typing.Optional[float] = pydantic.Field(default=None)
    """
    Pre-money valuation in USD
    """

    valuation_post_money: typing.Optional[float] = pydantic.Field(default=None)
    """
    Post-money valuation in USD
    """

    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    Currency code
    """

    equity_percentage: typing.Optional[float] = pydantic.Field(default=None)
    """
    Equity percentage
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
