# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .deals_service_providers_response_service_providers_item import DealsServiceProvidersResponseServiceProvidersItem


class DealsServiceProvidersResponse(UniversalBaseModel):
    deal_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Deal identifier
    """

    company_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Target company name
    """

    service_providers: typing.Optional[typing.List[DealsServiceProvidersResponseServiceProvidersItem]] = None
    total: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of service providers
    """

    data_sources: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
