# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DealsInvestorsResponseParticipantsItem(UniversalBaseModel):
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Investor name
    """

    entity_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Investor entity ID
    """

    role: typing.Optional[str] = pydantic.Field(default=None)
    """
    Role in deal (lead, participant)
    """

    amount_invested: typing.Optional[float] = pydantic.Field(default=None)
    """
    Amount invested in USD
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
