# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DealsBioResponse(UniversalBaseModel):
    deal_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique deal identifier
    """

    entity_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Always 'deal'
    """

    company_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Target company name
    """

    company_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Company entity ID
    """

    deal_date: typing.Optional[str] = pydantic.Field(default=None)
    """
    Deal date (YYYY-MM-DD)
    """

    deal_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Deal type
    """

    amount: typing.Optional[float] = pydantic.Field(default=None)
    """
    Deal amount in USD
    """

    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    Currency code
    """

    num_investors: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of investors
    """

    lead_investors: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Lead investor names
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Deal description
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Deal status
    """

    data_sources: typing.Optional[typing.List[str]] = None
    cached_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    Cache timestamp (ISO 8601)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
