# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawGeneralClient, RawGeneralClient


class GeneralClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawGeneralClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawGeneralClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawGeneralClient
        """
        return self._raw_client

    def search(
        self, *, limit: typing.Optional[int] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Search across all entity types (companies, people, investors, funds, deals, etc.) in a unified query. Returns matching entities with their type and basic information. Use this for broad discovery before drilling into specific entity types.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.general.search()
        """
        _response = self._raw_client.search(limit=limit, request_options=request_options)
        return _response.data

    def search_shared(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Dict[str, typing.Any]:
        """
        Search for entities shared across your organization. Returns entities that multiple team members have accessed or tagged. Useful for discovering commonly referenced companies, investors, or people within your team.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.general.search_shared()
        """
        _response = self._raw_client.search_shared(request_options=request_options)
        return _response.data

    def entity_people(
        self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get people associated with any entity (company employees, fund team members, investor partners, etc.). Returns names, titles, and LinkedIn profiles for key people.

        Parameters
        ----------
        entity_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.general.entity_people(
            entity_id="openai",
        )
        """
        _response = self._raw_client.entity_people(entity_id, request_options=request_options)
        return _response.data

    def entity_locations(
        self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get office locations for any entity. Returns headquarters and branch office addresses with city, state, country, and full address details.

        Parameters
        ----------
        entity_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.general.entity_locations(
            entity_id="openai",
        )
        """
        _response = self._raw_client.entity_locations(entity_id, request_options=request_options)
        return _response.data

    def entity_affiliates(
        self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get affiliated entities and subsidiaries for any entity. Returns parent companies, subsidiaries, and related entities with ownership information.

        Parameters
        ----------
        entity_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.general.entity_affiliates(
            entity_id="openai",
        )
        """
        _response = self._raw_client.entity_affiliates(entity_id, request_options=request_options)
        return _response.data

    def entity_news(
        self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get recent news articles and mentions for any entity. Returns article titles, URLs, sources, publication dates, and snippets. Useful for tracking announcements, funding news, and company updates.

        Parameters
        ----------
        entity_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.general.entity_news(
            entity_id="openai",
        )
        """
        _response = self._raw_client.entity_news(entity_id, request_options=request_options)
        return _response.data

    def entity_updates(
        self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get changelog of data updates for any entity. Returns history of changes to the entity's profile, tracking when information was added or modified. Useful for monitoring data freshness.

        Parameters
        ----------
        entity_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.general.entity_updates(
            entity_id="openai",
        )
        """
        _response = self._raw_client.entity_updates(entity_id, request_options=request_options)
        return _response.data


class AsyncGeneralClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawGeneralClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawGeneralClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawGeneralClient
        """
        return self._raw_client

    async def search(
        self, *, limit: typing.Optional[int] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Search across all entity types (companies, people, investors, funds, deals, etc.) in a unified query. Returns matching entities with their type and basic information. Use this for broad discovery before drilling into specific entity types.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.general.search()


        asyncio.run(main())
        """
        _response = await self._raw_client.search(limit=limit, request_options=request_options)
        return _response.data

    async def search_shared(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Search for entities shared across your organization. Returns entities that multiple team members have accessed or tagged. Useful for discovering commonly referenced companies, investors, or people within your team.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.general.search_shared()


        asyncio.run(main())
        """
        _response = await self._raw_client.search_shared(request_options=request_options)
        return _response.data

    async def entity_people(
        self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get people associated with any entity (company employees, fund team members, investor partners, etc.). Returns names, titles, and LinkedIn profiles for key people.

        Parameters
        ----------
        entity_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.general.entity_people(
                entity_id="openai",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.entity_people(entity_id, request_options=request_options)
        return _response.data

    async def entity_locations(
        self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get office locations for any entity. Returns headquarters and branch office addresses with city, state, country, and full address details.

        Parameters
        ----------
        entity_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.general.entity_locations(
                entity_id="openai",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.entity_locations(entity_id, request_options=request_options)
        return _response.data

    async def entity_affiliates(
        self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get affiliated entities and subsidiaries for any entity. Returns parent companies, subsidiaries, and related entities with ownership information.

        Parameters
        ----------
        entity_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.general.entity_affiliates(
                entity_id="openai",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.entity_affiliates(entity_id, request_options=request_options)
        return _response.data

    async def entity_news(
        self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get recent news articles and mentions for any entity. Returns article titles, URLs, sources, publication dates, and snippets. Useful for tracking announcements, funding news, and company updates.

        Parameters
        ----------
        entity_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.general.entity_news(
                entity_id="openai",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.entity_news(entity_id, request_options=request_options)
        return _response.data

    async def entity_updates(
        self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get changelog of data updates for any entity. Returns history of changes to the entity's profile, tracking when information was added or modified. Useful for monitoring data freshness.

        Parameters
        ----------
        entity_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.general.entity_updates(
                entity_id="openai",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.entity_updates(entity_id, request_options=request_options)
        return _response.data
