# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .funds_active_investments_response_investments_item import FundsActiveInvestmentsResponseInvestmentsItem


class FundsActiveInvestmentsResponse(UniversalBaseModel):
    entity_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Fund entity ID
    """

    investments: typing.Optional[typing.List[FundsActiveInvestmentsResponseInvestmentsItem]] = None
    total: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total investments
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Results limit
    """

    data_sources: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
