# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .service_providers_deals_response_deals_item import ServiceProvidersDealsResponseDealsItem


class ServiceProvidersDealsResponse(UniversalBaseModel):
    entity_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Provider entity ID
    """

    deals: typing.Optional[typing.List[ServiceProvidersDealsResponseDealsItem]] = None
    total: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total deals
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
