# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .service_providers_search_response_results_item import ServiceProvidersSearchResponseResultsItem


class ServiceProvidersSearchResponse(UniversalBaseModel):
    query: typing.Optional[str] = pydantic.Field(default=None)
    """
    The search query that was executed
    """

    results: typing.Optional[typing.List[ServiceProvidersSearchResponseResultsItem]] = pydantic.Field(default=None)
    """
    Array of matching results
    """

    total_results: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of matching results
    """

    page: typing.Optional[int] = pydantic.Field(default=None)
    """
    Current page number
    """

    page_size: typing.Optional[int] = pydantic.Field(default=None)
    """
    Results per page
    """

    total: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total matching results
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Results limit
    """

    provider_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Provider type filter that was applied
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
