# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .service_providers_investors_response_investors_item import ServiceProvidersInvestorsResponseInvestorsItem


class ServiceProvidersInvestorsResponse(UniversalBaseModel):
    entity_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Provider entity ID
    """

    investors: typing.Optional[typing.List[ServiceProvidersInvestorsResponseInvestorsItem]] = None
    total: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total investor clients
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
