# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .fundamentals_lookup_table_values_response_values_item import FundamentalsLookupTableValuesResponseValuesItem


class FundamentalsLookupTableValuesResponse(UniversalBaseModel):
    table_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Lookup table identifier
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Table name
    """

    values: typing.Optional[typing.List[FundamentalsLookupTableValuesResponseValuesItem]] = pydantic.Field(default=None)
    """
    Table values
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
