# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .fundamentals_sandbox_response_companies_item import FundamentalsSandboxResponseCompaniesItem
from .fundamentals_sandbox_response_investors_item import FundamentalsSandboxResponseInvestorsItem
from .fundamentals_sandbox_response_people_item import FundamentalsSandboxResponsePeopleItem


class FundamentalsSandboxResponse(UniversalBaseModel):
    companies: typing.Optional[typing.List[FundamentalsSandboxResponseCompaniesItem]] = pydantic.Field(default=None)
    """
    Pre-loaded sample company entities
    """

    investors: typing.Optional[typing.List[FundamentalsSandboxResponseInvestorsItem]] = pydantic.Field(default=None)
    """
    Pre-loaded sample investor entities
    """

    people: typing.Optional[typing.List[FundamentalsSandboxResponsePeopleItem]] = pydantic.Field(default=None)
    """
    Pre-loaded sample person entities
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
