# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CompaniesActiveInvestorsResponseInvestorsItem(UniversalBaseModel):
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Investor name
    """

    investor_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Investor type (venture_capital, corporate, individual)
    """

    website: typing.Optional[str] = pydantic.Field(default=None)
    """
    Investor website
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Brief description
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
