# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CompaniesFinancingRecentResponseRoundsItem(UniversalBaseModel):
    round_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Round type (e.g., Series A)
    """

    amount: typing.Optional[float] = pydantic.Field(default=None)
    """
    Amount raised in USD
    """

    date: typing.Optional[str] = pydantic.Field(default=None)
    """
    Round date (YYYY-MM-DD)
    """

    investors: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Investor names
    """

    valuation: typing.Optional[float] = pydantic.Field(default=None)
    """
    Valuation at round
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
