# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .companies_debt_financing_recent_response_round import CompaniesDebtFinancingRecentResponseRound


class CompaniesDebtFinancingRecentResponse(UniversalBaseModel):
    entity_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Company entity ID
    """

    round: typing.Optional[CompaniesDebtFinancingRecentResponseRound] = pydantic.Field(default=None)
    """
    Most recent debt financing round (null if none)
    """

    data_sources: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
