# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ChangeEnvironmentResponseV2(UniversalBaseModel):
    success: bool = pydantic.Field()
    """
    Whether the environment change was successful
    """

    message: str = pydantic.Field()
    """
    Human-readable status message
    """

    collection_name: str = pydantic.Field()
    """
    Name of the collection that was moved
    """

    previous_environment: str = pydantic.Field()
    """
    The environment the collection was moved from
    """

    new_environment: str = pydantic.Field()
    """
    The environment the collection was moved to
    """

    files_moved: int = pydantic.Field()
    """
    Number of files associated with the collection (all preserved)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
