# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CollectionItemV2(UniversalBaseModel):
    environment: typing.Optional[str] = pydantic.Field(default=None)
    """
    Environment the collection belongs to
    """

    is_active: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the collection is active
    """

    created_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    ISO 8601 timestamp of when the collection was created
    """

    request_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of API requests made against this collection
    """

    database_name: str = pydantic.Field()
    """
    Name of the collection database
    """

    file_count: int = pydantic.Field()
    """
    Total number of files indexed in this collection
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
