# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FilesPage(UniversalBaseModel):
    """
    Pagination information for the files array
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Maximum number of files returned per page
    """

    next_cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Cursor for fetching the next page of files
    """

    total_estimated: typing.Optional[int] = pydantic.Field(default=None)
    """
    Estimated total number of files in the job
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
