# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .job_progress_current_stage import JobProgressCurrentStage


class JobProgress(UniversalBaseModel):
    """
    Detailed progress information for a running job
    """

    current_stage: typing.Optional[JobProgressCurrentStage] = pydantic.Field(default=None)
    """
    Current processing stage
    """

    stage_description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable description of the current stage
    """

    files_total: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of files to process
    """

    files_processed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of files processed so far
    """

    files_failed: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of files that failed
    """

    files_skipped: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of files skipped (already indexed, etc.)
    """

    elapsed_seconds: typing.Optional[int] = pydantic.Field(default=None)
    """
    Seconds elapsed since job started
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
