# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .file_status import FileStatus
from .files_page import FilesPage
from .job_billing import JobBilling
from .job_progress import JobProgress
from .job_result import JobResult
from .job_status import JobStatus
from .job_status_response_v2job_type import JobStatusResponseV2JobType


class JobStatusResponseV2(UniversalBaseModel):
    """
    Comprehensive job status response with progress details, file statuses, and billing information.
    """

    job_id: str = pydantic.Field()
    """
    Unique identifier for the job
    """

    collection_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the collection being indexed
    """

    job_type: typing.Optional[JobStatusResponseV2JobType] = pydantic.Field(default=None)
    """
    Type of indexing job
    """

    status: JobStatus = pydantic.Field()
    """
    Current job status
    """

    progress_message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable progress message
    """

    progress: typing.Optional[JobProgress] = pydantic.Field(default=None)
    """
    Detailed progress information including current stage and file counts
    """

    files: typing.Optional[typing.List[FileStatus]] = pydantic.Field(default=None)
    """
    Array of individual file statuses
    """

    files_page: typing.Optional[FilesPage] = pydantic.Field(default=None)
    """
    Pagination info for the files array
    """

    result: typing.Optional[JobResult] = pydantic.Field(default=None)
    """
    Final result summary (present when completed or failed)
    """

    billing: typing.Optional[JobBilling] = pydantic.Field(default=None)
    """
    Billing details including cost, credits used, and remaining balance. Present when status is 'completed' or 'completed_with_failures'.
    """

    error_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Error code if job failed
    """

    error_message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Error message if job failed
    """

    cancelled_by: typing.Optional[str] = pydantic.Field(default=None)
    """
    Who cancelled the job (if cancelled)
    """

    cancelled_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the job was cancelled
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the job was created
    """

    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the job was last updated
    """

    started_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When processing started (null if pending)
    """

    completed_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the job finished (completed, failed, or cancelled)
    """

    estimated_time_remaining_seconds: typing.Optional[int] = pydantic.Field(default=None)
    """
    Estimated seconds until completion
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
