# This file was auto-generated by Fern from our API Definition.

import typing

JobStatusResponseV2JobType = typing.Union[
    typing.Literal[
        "index_s3", "index_s3_file", "index_s3_directory", "index_gcs", "index_gcs_file", "index_gcs_directory"
    ],
    typing.Any,
]
