# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class QueryStreamTextEvent(UniversalBaseModel):
    """
    Incremental text chunk of the AI response.
    """

    seq: typing.Optional[int] = pydantic.Field(default=None)
    """
    Monotonically increasing sequence number within the stream
    """

    run_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Identifier for the current agent run
    """

    data: str = pydantic.Field()
    """
    Text fragment of the AI-generated response
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
