# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class QueryStreamToolStartEvent(UniversalBaseModel):
    """
    Emitted when the AI agent begins a knowledge-base search.
    """

    seq: typing.Optional[int] = pydantic.Field(default=None)
    """
    Monotonically increasing sequence number within the stream
    """

    run_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Identifier for the current agent run
    """

    tool_call_id: str = pydantic.Field()
    """
    Correlates this start with the corresponding tool.end event
    """

    name: str = pydantic.Field()
    """
    Tool name, e.g. searchKnowledgeBase
    """

    args: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Arguments passed to the tool (e.g. {"query": "...", "topK": 10})
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
