# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class LpsBioResponseData(UniversalBaseModel):
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    LP name
    """

    website: typing.Optional[str] = pydantic.Field(default=None)
    """
    Website URL
    """

    industry: typing.Optional[str] = pydantic.Field(default=None)
    """
    LP industry classification
    """

    employee_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of employees
    """

    summary: typing.Optional[str] = pydantic.Field(default=None)
    """
    LP description/summary
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
