# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .lps_bio_response_data import LpsBioResponseData


class LpsBioResponse(UniversalBaseModel):
    entity_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    LP entity ID
    """

    identifier: typing.Optional[str] = pydantic.Field(default=None)
    """
    LP identifier
    """

    entity_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Always 'limited_partner'
    """

    display_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    LP display name
    """

    data: typing.Optional[LpsBioResponseData] = None
    note: typing.Optional[str] = pydantic.Field(default=None)
    """
    Data availability note
    """

    industry: typing.Optional[str] = pydantic.Field(default=None)
    """
    LP industry classification
    """

    employee_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of employees
    """

    summary: typing.Optional[str] = pydantic.Field(default=None)
    """
    LP description/summary
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
