# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .lps_search_response_results_item import LpsSearchResponseResultsItem


class LpsSearchResponse(UniversalBaseModel):
    query: typing.Optional[str] = pydantic.Field(default=None)
    """
    The search query that was executed
    """

    results: typing.Optional[typing.List[LpsSearchResponseResultsItem]] = pydantic.Field(default=None)
    """
    Array of matching results
    """

    total: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of matching results
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Maximum results requested
    """

    note: typing.Optional[str] = pydantic.Field(default=None)
    """
    Data availability note
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
