# This file was auto-generated by Fern from our API Definition.

import typing

ChangeEnvironmentRequestV2NewEnvironment = typing.Union[
    typing.Literal["development", "staging", "production"], typing.Any
]
