# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .general_entity_affiliates_response import GeneralEntityAffiliatesResponse
    from .general_entity_affiliates_response_affiliates_item import GeneralEntityAffiliatesResponseAffiliatesItem
    from .general_entity_locations_response import GeneralEntityLocationsResponse
    from .general_entity_locations_response_locations_item import GeneralEntityLocationsResponseLocationsItem
    from .general_entity_news_response import GeneralEntityNewsResponse
    from .general_entity_news_response_news_item import GeneralEntityNewsResponseNewsItem
    from .general_entity_people_response import GeneralEntityPeopleResponse
    from .general_entity_people_response_people_item import GeneralEntityPeopleResponsePeopleItem
    from .general_search_request_entity_type import GeneralSearchRequestEntityType
    from .general_search_response import GeneralSearchResponse
    from .general_search_response_results_item import GeneralSearchResponseResultsItem
    from .general_search_shared_response import GeneralSearchSharedResponse
    from .general_search_shared_response_results_item import GeneralSearchSharedResponseResultsItem
_dynamic_imports: typing.Dict[str, str] = {
    "GeneralEntityAffiliatesResponse": ".general_entity_affiliates_response",
    "GeneralEntityAffiliatesResponseAffiliatesItem": ".general_entity_affiliates_response_affiliates_item",
    "GeneralEntityLocationsResponse": ".general_entity_locations_response",
    "GeneralEntityLocationsResponseLocationsItem": ".general_entity_locations_response_locations_item",
    "GeneralEntityNewsResponse": ".general_entity_news_response",
    "GeneralEntityNewsResponseNewsItem": ".general_entity_news_response_news_item",
    "GeneralEntityPeopleResponse": ".general_entity_people_response",
    "GeneralEntityPeopleResponsePeopleItem": ".general_entity_people_response_people_item",
    "GeneralSearchRequestEntityType": ".general_search_request_entity_type",
    "GeneralSearchResponse": ".general_search_response",
    "GeneralSearchResponseResultsItem": ".general_search_response_results_item",
    "GeneralSearchSharedResponse": ".general_search_shared_response",
    "GeneralSearchSharedResponseResultsItem": ".general_search_shared_response_results_item",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "GeneralEntityAffiliatesResponse",
    "GeneralEntityAffiliatesResponseAffiliatesItem",
    "GeneralEntityLocationsResponse",
    "GeneralEntityLocationsResponseLocationsItem",
    "GeneralEntityNewsResponse",
    "GeneralEntityNewsResponseNewsItem",
    "GeneralEntityPeopleResponse",
    "GeneralEntityPeopleResponsePeopleItem",
    "GeneralSearchRequestEntityType",
    "GeneralSearchResponse",
    "GeneralSearchResponseResultsItem",
    "GeneralSearchSharedResponse",
    "GeneralSearchSharedResponseResultsItem",
]
