# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .general_entity_locations_response_locations_item import GeneralEntityLocationsResponseLocationsItem


class GeneralEntityLocationsResponse(UniversalBaseModel):
    entity_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Entity identifier
    """

    locations: typing.Optional[typing.List[GeneralEntityLocationsResponseLocationsItem]] = None
    total_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of locations
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
