# This file was auto-generated by Fern from our API Definition.

import typing

GeneralSearchRequestEntityType = typing.Union[
    typing.Literal["company", "person", "investor", "fund", "deal", "lp", "service_provider"], typing.Any
]
