# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawSandboxDataClient, RawSandboxDataClient
from .types.fundamentals_lookup_table_values_response import FundamentalsLookupTableValuesResponse
from .types.fundamentals_lookup_tables_response import FundamentalsLookupTablesResponse
from .types.fundamentals_sandbox_response import FundamentalsSandboxResponse


class SandboxDataClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSandboxDataClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSandboxDataClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSandboxDataClient
        """
        return self._raw_client

    def fundamentals_sandbox(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FundamentalsSandboxResponse:
        """
        Get sample entities for testing and development. Returns mock company, person, investor, and fund data for sandbox environment testing.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FundamentalsSandboxResponse
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.sandbox_data.fundamentals_sandbox()
        """
        _response = self._raw_client.fundamentals_sandbox(request_options=request_options)
        return _response.data

    def fundamentals_lookup_tables(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FundamentalsLookupTablesResponse:
        """
        Get available reference lookup tables including industry codes, country codes, and entity type classifications. Returns list of available tables with descriptions.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FundamentalsLookupTablesResponse
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.sandbox_data.fundamentals_lookup_tables()
        """
        _response = self._raw_client.fundamentals_lookup_tables(request_options=request_options)
        return _response.data

    def fundamentals_lookup_table_values(
        self, table_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FundamentalsLookupTableValuesResponse:
        """
        Get values from a specific lookup table. Returns table data with codes, descriptions, and hierarchical relationships for reference data.

        Parameters
        ----------
        table_id : str
            Lookup table ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FundamentalsLookupTableValuesResponse
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.sandbox_data.fundamentals_lookup_table_values(
            table_id="sectors",
        )
        """
        _response = self._raw_client.fundamentals_lookup_table_values(table_id, request_options=request_options)
        return _response.data


class AsyncSandboxDataClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSandboxDataClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSandboxDataClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSandboxDataClient
        """
        return self._raw_client

    async def fundamentals_sandbox(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FundamentalsSandboxResponse:
        """
        Get sample entities for testing and development. Returns mock company, person, investor, and fund data for sandbox environment testing.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FundamentalsSandboxResponse
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.sandbox_data.fundamentals_sandbox()


        asyncio.run(main())
        """
        _response = await self._raw_client.fundamentals_sandbox(request_options=request_options)
        return _response.data

    async def fundamentals_lookup_tables(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FundamentalsLookupTablesResponse:
        """
        Get available reference lookup tables including industry codes, country codes, and entity type classifications. Returns list of available tables with descriptions.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FundamentalsLookupTablesResponse
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.sandbox_data.fundamentals_lookup_tables()


        asyncio.run(main())
        """
        _response = await self._raw_client.fundamentals_lookup_tables(request_options=request_options)
        return _response.data

    async def fundamentals_lookup_table_values(
        self, table_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FundamentalsLookupTableValuesResponse:
        """
        Get values from a specific lookup table. Returns table data with codes, descriptions, and hierarchical relationships for reference data.

        Parameters
        ----------
        table_id : str
            Lookup table ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FundamentalsLookupTableValuesResponse
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.sandbox_data.fundamentals_lookup_table_values(
                table_id="sectors",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.fundamentals_lookup_table_values(table_id, request_options=request_options)
        return _response.data
