# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawCompaniesClient, RawCompaniesClient


class CompaniesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCompaniesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCompaniesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCompaniesClient
        """
        return self._raw_client

    def search(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Dict[str, typing.Any]:
        """
        Search for companies by name, industry, or location. Returns matching company profiles with employee count, industry classification, founding date, and headquarters. Use this to find company entity IDs for detailed lookups.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.companies.search()
        """
        _response = self._raw_client.search(request_options=request_options)
        return _response.data

    def bio(self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Get comprehensive company profile including description, founding date, headquarters location, employee count, industry classification, and social media profiles. This is the primary endpoint for company overview data.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Company bio retrieved successfully

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.companies.bio(
            company_id="019cb8ac-adee-749e-a75e-a1c236f20f72",
        )
        """
        _response = self._raw_client.bio(company_id, request_options=request_options)
        return _response.data

    def industries(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get industry classifications including NAICS codes, SIC codes, and industry descriptions. Useful for filtering companies by vertical or sector.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.companies.industries(
            company_id="openai.com",
        )
        """
        _response = self._raw_client.industries(company_id, request_options=request_options)
        return _response.data

    def financials(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get financial statements for public companies including revenue, net income, assets, and liabilities. Returns most recent fiscal year data or specific year if requested.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.companies.financials(
            company_id="ody_co_sample_msft",
        )
        """
        _response = self._raw_client.financials(company_id, request_options=request_options)
        return _response.data

    def financials_recent(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get most recent financial statements for public companies. Convenience endpoint that automatically returns the latest available fiscal year data.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.companies.financials_recent(
            company_id="openai.com",
        )
        """
        _response = self._raw_client.financials_recent(company_id, request_options=request_options)
        return _response.data

    def financing_recent(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get most recent funding rounds including round type, amount raised, investors, and valuation. Returns detailed information about the latest equity financing event.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.companies.financing_recent(
            company_id="openai.com",
        )
        """
        _response = self._raw_client.financing_recent(company_id, request_options=request_options)
        return _response.data

    def active_investors(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Get current investors in the company from recent funding rounds. Returns investor names, types, and contact information.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Active investors retrieved successfully

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.companies.active_investors(
            company_id="openai.com",
        )
        """
        _response = self._raw_client.active_investors(company_id, request_options=request_options)
        return _response.data

    def all_investors(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get complete investor history including historical investors from all funding rounds. Returns comprehensive list of all investors who have participated in company financing.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.companies.all_investors(
            company_id="openai.com",
        )
        """
        _response = self._raw_client.all_investors(company_id, request_options=request_options)
        return _response.data

    def deals(self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Get all deals for a company including funding rounds and acquisitions. Each deal includes the deal type, round name, investors involved, amount raised, and status. Funding rounds are sourced from investor data, while acquisitions are sourced from M&A records.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Company deals retrieved successfully

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.companies.deals(
            company_id="openai.com",
        )
        """
        _response = self._raw_client.deals(company_id, request_options=request_options)
        return _response.data

    def service_providers(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get service providers working with the company including legal counsel, accounting firms, and consultants. Returns firm names, service types, and engagement information.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.companies.service_providers(
            company_id="openai.com",
        )
        """
        _response = self._raw_client.service_providers(company_id, request_options=request_options)
        return _response.data

    def service_providers_deal(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get service providers involved in specific financing deals including investment bankers, legal advisors, and financial consultants. Returns provider details specific to fundraising transactions.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.companies.service_providers_deal(
            company_id="openai.com",
        )
        """
        _response = self._raw_client.service_providers_deal(company_id, request_options=request_options)
        return _response.data

    def debt_financing_recent(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get most recent debt financing rounds including venture debt, credit lines, and loans. Returns lender information, amounts, and terms.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.companies.debt_financing_recent(
            company_id="openai.com",
        )
        """
        _response = self._raw_client.debt_financing_recent(company_id, request_options=request_options)
        return _response.data

    def similar(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get companies similar to this one based on industry, size, and business model. Returns competitor and peer company information with similarity scores.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.companies.similar(
            company_id="openai.com",
        )
        """
        _response = self._raw_client.similar(company_id, request_options=request_options)
        return _response.data

    def social_analytics(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get social media metrics including LinkedIn followers, Twitter engagement, and Facebook presence. Useful for measuring company online visibility and growth.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.companies.social_analytics(
            company_id="openai.com",
        )
        """
        _response = self._raw_client.social_analytics(company_id, request_options=request_options)
        return _response.data

    def vc_exit_predictions(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Coming Soon: Get predicted likelihood and timeline for company exit events (IPO or acquisition). Will return ML-based exit probability scores and estimated exit valuation ranges when implemented.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.companies.vc_exit_predictions(
            company_id="openai.com",
        )
        """
        _response = self._raw_client.vc_exit_predictions(company_id, request_options=request_options)
        return _response.data

    def updates(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get changelog of updates to company profile data. Returns history of changes to company information with timestamps and modified fields.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.companies.updates(
            company_id="openai.com",
        )
        """
        _response = self._raw_client.updates(company_id, request_options=request_options)
        return _response.data


class AsyncCompaniesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCompaniesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCompaniesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCompaniesClient
        """
        return self._raw_client

    async def search(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Dict[str, typing.Any]:
        """
        Search for companies by name, industry, or location. Returns matching company profiles with employee count, industry classification, founding date, and headquarters. Use this to find company entity IDs for detailed lookups.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.companies.search()


        asyncio.run(main())
        """
        _response = await self._raw_client.search(request_options=request_options)
        return _response.data

    async def bio(self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Get comprehensive company profile including description, founding date, headquarters location, employee count, industry classification, and social media profiles. This is the primary endpoint for company overview data.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Company bio retrieved successfully

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.companies.bio(
                company_id="019cb8ac-adee-749e-a75e-a1c236f20f72",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.bio(company_id, request_options=request_options)
        return _response.data

    async def industries(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get industry classifications including NAICS codes, SIC codes, and industry descriptions. Useful for filtering companies by vertical or sector.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.companies.industries(
                company_id="openai.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.industries(company_id, request_options=request_options)
        return _response.data

    async def financials(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get financial statements for public companies including revenue, net income, assets, and liabilities. Returns most recent fiscal year data or specific year if requested.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.companies.financials(
                company_id="ody_co_sample_msft",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.financials(company_id, request_options=request_options)
        return _response.data

    async def financials_recent(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get most recent financial statements for public companies. Convenience endpoint that automatically returns the latest available fiscal year data.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.companies.financials_recent(
                company_id="openai.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.financials_recent(company_id, request_options=request_options)
        return _response.data

    async def financing_recent(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get most recent funding rounds including round type, amount raised, investors, and valuation. Returns detailed information about the latest equity financing event.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.companies.financing_recent(
                company_id="openai.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.financing_recent(company_id, request_options=request_options)
        return _response.data

    async def active_investors(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Get current investors in the company from recent funding rounds. Returns investor names, types, and contact information.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Active investors retrieved successfully

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.companies.active_investors(
                company_id="openai.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.active_investors(company_id, request_options=request_options)
        return _response.data

    async def all_investors(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get complete investor history including historical investors from all funding rounds. Returns comprehensive list of all investors who have participated in company financing.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.companies.all_investors(
                company_id="openai.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.all_investors(company_id, request_options=request_options)
        return _response.data

    async def deals(self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> typing.Any:
        """
        Get all deals for a company including funding rounds and acquisitions. Each deal includes the deal type, round name, investors involved, amount raised, and status. Funding rounds are sourced from investor data, while acquisitions are sourced from M&A records.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Company deals retrieved successfully

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.companies.deals(
                company_id="openai.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.deals(company_id, request_options=request_options)
        return _response.data

    async def service_providers(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get service providers working with the company including legal counsel, accounting firms, and consultants. Returns firm names, service types, and engagement information.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.companies.service_providers(
                company_id="openai.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.service_providers(company_id, request_options=request_options)
        return _response.data

    async def service_providers_deal(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get service providers involved in specific financing deals including investment bankers, legal advisors, and financial consultants. Returns provider details specific to fundraising transactions.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.companies.service_providers_deal(
                company_id="openai.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.service_providers_deal(company_id, request_options=request_options)
        return _response.data

    async def debt_financing_recent(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get most recent debt financing rounds including venture debt, credit lines, and loans. Returns lender information, amounts, and terms.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.companies.debt_financing_recent(
                company_id="openai.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.debt_financing_recent(company_id, request_options=request_options)
        return _response.data

    async def similar(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get companies similar to this one based on industry, size, and business model. Returns competitor and peer company information with similarity scores.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.companies.similar(
                company_id="openai.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.similar(company_id, request_options=request_options)
        return _response.data

    async def social_analytics(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get social media metrics including LinkedIn followers, Twitter engagement, and Facebook presence. Useful for measuring company online visibility and growth.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.companies.social_analytics(
                company_id="openai.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.social_analytics(company_id, request_options=request_options)
        return _response.data

    async def vc_exit_predictions(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Coming Soon: Get predicted likelihood and timeline for company exit events (IPO or acquisition). Will return ML-based exit probability scores and estimated exit valuation ranges when implemented.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.companies.vc_exit_predictions(
                company_id="openai.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.vc_exit_predictions(company_id, request_options=request_options)
        return _response.data

    async def updates(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get changelog of updates to company profile data. Returns history of changes to company information with timestamps and modified fields.

        Parameters
        ----------
        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.companies.updates(
                company_id="openai.com",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.updates(company_id, request_options=request_options)
        return _response.data
