# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawPatentsClient, RawPatentsClient


class PatentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPatentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPatentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPatentsClient
        """
        return self._raw_client

    def search(
        self, *, limit: typing.Optional[int] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Search for patents by title, inventor, assignee, or classification. Returns matching patents with patent numbers, titles, filing dates, and status.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.patents.search()
        """
        _response = self._raw_client.search(limit=limit, request_options=request_options)
        return _response.data

    def get_by_id(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get detailed patent information including abstract, claims, inventors, citations, and prosecution history. Returns comprehensive patent profile.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.patents.get_by_id(
            id="deal_openai_0",
        )
        """
        _response = self._raw_client.get_by_id(id, request_options=request_options)
        return _response.data

    def get_file(
        self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Download patent file wrapper or PDF document. Returns patent documentation and prosecution history files.

        Parameters
        ----------
        entity_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.patents.get_file(
            entity_id="US11234567B2",
        )
        """
        _response = self._raw_client.get_file(entity_id, request_options=request_options)
        return _response.data


class AsyncPatentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPatentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPatentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPatentsClient
        """
        return self._raw_client

    async def search(
        self, *, limit: typing.Optional[int] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Search for patents by title, inventor, assignee, or classification. Returns matching patents with patent numbers, titles, filing dates, and status.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum results

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.patents.search()


        asyncio.run(main())
        """
        _response = await self._raw_client.search(limit=limit, request_options=request_options)
        return _response.data

    async def get_by_id(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get detailed patent information including abstract, claims, inventors, citations, and prosecution history. Returns comprehensive patent profile.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.patents.get_by_id(
                id="deal_openai_0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_by_id(id, request_options=request_options)
        return _response.data

    async def get_file(
        self, entity_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Download patent file wrapper or PDF document. Returns patent documentation and prosecution history files.

        Parameters
        ----------
        entity_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.patents.get_file(
                entity_id="US11234567B2",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_file(entity_id, request_options=request_options)
        return _response.data
