# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawServiceProvidersClient, RawServiceProvidersClient


class ServiceProvidersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawServiceProvidersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawServiceProvidersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawServiceProvidersClient
        """
        return self._raw_client

    def search(
        self,
        *,
        limit: typing.Optional[int] = None,
        provider_type: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Search for service providers including law firms, accounting firms, investment banks, and consultants. Returns matching provider profiles with specializations and notable clients.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum results

        provider_type : typing.Optional[str]
            Provider type filter

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.service_providers.search()
        """
        _response = self._raw_client.search(limit=limit, provider_type=provider_type, request_options=request_options)
        return _response.data

    def bio(
        self, provider_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get comprehensive service provider profile including firm description, practice areas, office locations, and notable work. This is the primary endpoint for provider overview data.

        Parameters
        ----------
        provider_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.service_providers.bio(
            provider_id="wilson-sonsini",
        )
        """
        _response = self._raw_client.bio(provider_id, request_options=request_options)
        return _response.data

    def companies(
        self, provider_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get companies that have engaged this service provider. Returns client list with engagement types and sectors served.

        Parameters
        ----------
        provider_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.service_providers.companies(
            provider_id="wilson-sonsini",
        )
        """
        _response = self._raw_client.companies(provider_id, request_options=request_options)
        return _response.data

    def deals(
        self, provider_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get deals where this provider was involved as advisor, counsel, or banker. Returns transaction history with roles and deal values.

        Parameters
        ----------
        provider_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.service_providers.deals(
            provider_id="wilson-sonsini",
        )
        """
        _response = self._raw_client.deals(provider_id, request_options=request_options)
        return _response.data

    def investors(
        self, provider_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get investors that have engaged this service provider. Returns investor clients with engagement types and fund formation work.

        Parameters
        ----------
        provider_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.service_providers.investors(
            provider_id="wilson-sonsini",
        )
        """
        _response = self._raw_client.investors(provider_id, request_options=request_options)
        return _response.data

    def funds(
        self, provider_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get funds that have engaged this service provider. Returns fund formation and compliance work with engagement details.

        Parameters
        ----------
        provider_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.service_providers.funds(
            provider_id="wilson-sonsini",
        )
        """
        _response = self._raw_client.funds(provider_id, request_options=request_options)
        return _response.data

    def limited_partners(
        self, provider_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get limited partners that have engaged this service provider. Returns LP clients with service types and relationship details.

        Parameters
        ----------
        provider_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.service_providers.limited_partners(
            provider_id="wilson-sonsini",
        )
        """
        _response = self._raw_client.limited_partners(provider_id, request_options=request_options)
        return _response.data

    def updates(
        self, provider_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get changelog of updates to service provider profile data. Returns history of changes including new engagements, office openings, and team changes with timestamps.

        Parameters
        ----------
        provider_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.service_providers.updates(
            provider_id="wilson-sonsini",
        )
        """
        _response = self._raw_client.updates(provider_id, request_options=request_options)
        return _response.data


class AsyncServiceProvidersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawServiceProvidersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawServiceProvidersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawServiceProvidersClient
        """
        return self._raw_client

    async def search(
        self,
        *,
        limit: typing.Optional[int] = None,
        provider_type: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Search for service providers including law firms, accounting firms, investment banks, and consultants. Returns matching provider profiles with specializations and notable clients.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum results

        provider_type : typing.Optional[str]
            Provider type filter

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.service_providers.search()


        asyncio.run(main())
        """
        _response = await self._raw_client.search(
            limit=limit, provider_type=provider_type, request_options=request_options
        )
        return _response.data

    async def bio(
        self, provider_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get comprehensive service provider profile including firm description, practice areas, office locations, and notable work. This is the primary endpoint for provider overview data.

        Parameters
        ----------
        provider_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.service_providers.bio(
                provider_id="wilson-sonsini",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.bio(provider_id, request_options=request_options)
        return _response.data

    async def companies(
        self, provider_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get companies that have engaged this service provider. Returns client list with engagement types and sectors served.

        Parameters
        ----------
        provider_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.service_providers.companies(
                provider_id="wilson-sonsini",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.companies(provider_id, request_options=request_options)
        return _response.data

    async def deals(
        self, provider_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get deals where this provider was involved as advisor, counsel, or banker. Returns transaction history with roles and deal values.

        Parameters
        ----------
        provider_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.service_providers.deals(
                provider_id="wilson-sonsini",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.deals(provider_id, request_options=request_options)
        return _response.data

    async def investors(
        self, provider_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get investors that have engaged this service provider. Returns investor clients with engagement types and fund formation work.

        Parameters
        ----------
        provider_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.service_providers.investors(
                provider_id="wilson-sonsini",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.investors(provider_id, request_options=request_options)
        return _response.data

    async def funds(
        self, provider_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get funds that have engaged this service provider. Returns fund formation and compliance work with engagement details.

        Parameters
        ----------
        provider_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.service_providers.funds(
                provider_id="wilson-sonsini",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.funds(provider_id, request_options=request_options)
        return _response.data

    async def limited_partners(
        self, provider_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get limited partners that have engaged this service provider. Returns LP clients with service types and relationship details.

        Parameters
        ----------
        provider_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.service_providers.limited_partners(
                provider_id="wilson-sonsini",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.limited_partners(provider_id, request_options=request_options)
        return _response.data

    async def updates(
        self, provider_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get changelog of updates to service provider profile data. Returns history of changes including new engagements, office openings, and team changes with timestamps.

        Parameters
        ----------
        provider_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.service_providers.updates(
                provider_id="wilson-sonsini",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.updates(provider_id, request_options=request_options)
        return _response.data
