# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawInvestorsClient, RawInvestorsClient
from .types.investors_active_investments_response import InvestorsActiveInvestmentsResponse
from .types.investors_bio_response import InvestorsBioResponse
from .types.investors_board_seats_response import InvestorsBoardSeatsResponse
from .types.investors_funds_latest_response import InvestorsFundsLatestResponse
from .types.investors_funds_response import InvestorsFundsResponse
from .types.investors_preferences_response import InvestorsPreferencesResponse
from .types.investors_search_response import InvestorsSearchResponse
from .types.investors_service_providers_deal_response import InvestorsServiceProvidersDealResponse
from .types.investors_service_providers_response import InvestorsServiceProvidersResponse


class InvestorsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawInvestorsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawInvestorsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawInvestorsClient
        """
        return self._raw_client

    def search(
        self,
        *,
        q: typing.Optional[str] = None,
        investor_type: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InvestorsSearchResponse:
        """
        Search for venture capital firms, angel investors, and institutional investors by name. Returns matching investor profiles with investment focus, portfolio size, and notable investments. Use this to find investor entity IDs for detailed lookups.

        Parameters
        ----------
        q : typing.Optional[str]
            Investor name or keyword (e.g., 'Sequoia Capital')

        investor_type : typing.Optional[str]
            Filter by investor type

        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Results per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvestorsSearchResponse
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.investors.search()
        """
        _response = self._raw_client.search(
            q=q, investor_type=investor_type, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    def bio(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> InvestorsBioResponse:
        """
        Get comprehensive investor profile including description, investment thesis, stage focus, sector focus, and notable portfolio companies. This is the primary endpoint for investor overview data.

        Parameters
        ----------
        id : str
            Investor name (e.g., 'Sequoia Capital') or entity ID from /investors/search

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvestorsBioResponse
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.investors.bio(
            id="ody_inv_019cb8ac-g789-749e-a75e-h7i880j64d16",
        )
        """
        _response = self._raw_client.bio(id, request_options=request_options)
        return _response.data

    def active_investments(
        self,
        id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InvestorsActiveInvestmentsResponse:
        """
        Get current portfolio companies that the investor has active positions in. Returns company names, investment dates, and current status.

        Supports pagination via `page` and `page_size` query parameters. Response includes `total_in_database` for the full count across all pages.

        Parameters
        ----------
        id : str
            Investor name (e.g., 'Sequoia Capital') or entity ID from /investors/search

        page : typing.Optional[int]
            Page number for pagination (default: 1)

        page_size : typing.Optional[int]
            Results per page (default: 50, max: 1000)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvestorsActiveInvestmentsResponse
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.investors.active_investments(
            id="deal_openai_0",
        )
        """
        _response = self._raw_client.active_investments(
            id, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    def preferences(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> InvestorsPreferencesResponse:
        """
        Get investment preferences including stage focus, sector preferences, geography, and typical check size. Useful for determining investment fit.

        Parameters
        ----------
        id : str
            Investor name (e.g., 'Sequoia Capital') or entity ID from /investors/search

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvestorsPreferencesResponse
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.investors.preferences(
            id="deal_openai_0",
        )
        """
        _response = self._raw_client.preferences(id, request_options=request_options)
        return _response.data

    def funds(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> InvestorsFundsResponse:
        """
        Get all funds managed by the investor including fund names, sizes, vintage years, and status. Returns complete fund portfolio for multi-fund investors.

        Parameters
        ----------
        id : str
            Investor name (e.g., 'Sequoia Capital') or entity ID from /investors/search

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvestorsFundsResponse
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.investors.funds(
            id="deal_openai_0",
        )
        """
        _response = self._raw_client.funds(id, request_options=request_options)
        return _response.data

    def funds_latest(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> InvestorsFundsLatestResponse:
        """
        Get information about the investor's most recent fund including size, vintage year, and deployment status. Useful for understanding current investment capacity.

        Parameters
        ----------
        id : str
            Investor name (e.g., 'Sequoia Capital') or entity ID from /investors/search

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvestorsFundsLatestResponse
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.investors.funds_latest(
            id="deal_openai_0",
        )
        """
        _response = self._raw_client.funds_latest(id, request_options=request_options)
        return _response.data

    def board_seats(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> InvestorsBoardSeatsResponse:
        """
        Get board seats held by the investor's team members. Returns companies where investor partners serve on the board of directors.

        Parameters
        ----------
        id : str
            Investor name (e.g., 'Sequoia Capital') or entity ID from /investors/search

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvestorsBoardSeatsResponse
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.investors.board_seats(
            id="deal_openai_0",
        )
        """
        _response = self._raw_client.board_seats(id, request_options=request_options)
        return _response.data

    def service_providers(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> InvestorsServiceProvidersResponse:
        """
        Get service providers used by the investor including legal counsel, fund administrators, and consultants. Returns firm names and service types.

        Parameters
        ----------
        id : str
            Investor name (e.g., 'Sequoia Capital') or entity ID from /investors/search

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvestorsServiceProvidersResponse
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.investors.service_providers(
            id="deal_openai_0",
        )
        """
        _response = self._raw_client.service_providers(id, request_options=request_options)
        return _response.data

    def service_providers_deal(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> InvestorsServiceProvidersDealResponse:
        """
        Get service providers involved in the investor's deal flow including transaction advisors and due diligence firms. Returns provider details specific to deal execution.

        Parameters
        ----------
        id : str
            Investor name (e.g., 'Sequoia Capital') or entity ID from /investors/search

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvestorsServiceProvidersDealResponse
            Successful response

        Examples
        --------
        from runcaptain import Captain

        client = Captain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )
        client.investors.service_providers_deal(
            id="deal_openai_0",
        )
        """
        _response = self._raw_client.service_providers_deal(id, request_options=request_options)
        return _response.data


class AsyncInvestorsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawInvestorsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawInvestorsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawInvestorsClient
        """
        return self._raw_client

    async def search(
        self,
        *,
        q: typing.Optional[str] = None,
        investor_type: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InvestorsSearchResponse:
        """
        Search for venture capital firms, angel investors, and institutional investors by name. Returns matching investor profiles with investment focus, portfolio size, and notable investments. Use this to find investor entity IDs for detailed lookups.

        Parameters
        ----------
        q : typing.Optional[str]
            Investor name or keyword (e.g., 'Sequoia Capital')

        investor_type : typing.Optional[str]
            Filter by investor type

        page : typing.Optional[int]
            Page number

        page_size : typing.Optional[int]
            Results per page

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvestorsSearchResponse
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.investors.search()


        asyncio.run(main())
        """
        _response = await self._raw_client.search(
            q=q, investor_type=investor_type, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def bio(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> InvestorsBioResponse:
        """
        Get comprehensive investor profile including description, investment thesis, stage focus, sector focus, and notable portfolio companies. This is the primary endpoint for investor overview data.

        Parameters
        ----------
        id : str
            Investor name (e.g., 'Sequoia Capital') or entity ID from /investors/search

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvestorsBioResponse
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.investors.bio(
                id="ody_inv_019cb8ac-g789-749e-a75e-h7i880j64d16",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.bio(id, request_options=request_options)
        return _response.data

    async def active_investments(
        self,
        id: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InvestorsActiveInvestmentsResponse:
        """
        Get current portfolio companies that the investor has active positions in. Returns company names, investment dates, and current status.

        Supports pagination via `page` and `page_size` query parameters. Response includes `total_in_database` for the full count across all pages.

        Parameters
        ----------
        id : str
            Investor name (e.g., 'Sequoia Capital') or entity ID from /investors/search

        page : typing.Optional[int]
            Page number for pagination (default: 1)

        page_size : typing.Optional[int]
            Results per page (default: 50, max: 1000)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvestorsActiveInvestmentsResponse
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.investors.active_investments(
                id="deal_openai_0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.active_investments(
            id, page=page, page_size=page_size, request_options=request_options
        )
        return _response.data

    async def preferences(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> InvestorsPreferencesResponse:
        """
        Get investment preferences including stage focus, sector preferences, geography, and typical check size. Useful for determining investment fit.

        Parameters
        ----------
        id : str
            Investor name (e.g., 'Sequoia Capital') or entity ID from /investors/search

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvestorsPreferencesResponse
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.investors.preferences(
                id="deal_openai_0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.preferences(id, request_options=request_options)
        return _response.data

    async def funds(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> InvestorsFundsResponse:
        """
        Get all funds managed by the investor including fund names, sizes, vintage years, and status. Returns complete fund portfolio for multi-fund investors.

        Parameters
        ----------
        id : str
            Investor name (e.g., 'Sequoia Capital') or entity ID from /investors/search

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvestorsFundsResponse
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.investors.funds(
                id="deal_openai_0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.funds(id, request_options=request_options)
        return _response.data

    async def funds_latest(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> InvestorsFundsLatestResponse:
        """
        Get information about the investor's most recent fund including size, vintage year, and deployment status. Useful for understanding current investment capacity.

        Parameters
        ----------
        id : str
            Investor name (e.g., 'Sequoia Capital') or entity ID from /investors/search

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvestorsFundsLatestResponse
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.investors.funds_latest(
                id="deal_openai_0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.funds_latest(id, request_options=request_options)
        return _response.data

    async def board_seats(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> InvestorsBoardSeatsResponse:
        """
        Get board seats held by the investor's team members. Returns companies where investor partners serve on the board of directors.

        Parameters
        ----------
        id : str
            Investor name (e.g., 'Sequoia Capital') or entity ID from /investors/search

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvestorsBoardSeatsResponse
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.investors.board_seats(
                id="deal_openai_0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.board_seats(id, request_options=request_options)
        return _response.data

    async def service_providers(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> InvestorsServiceProvidersResponse:
        """
        Get service providers used by the investor including legal counsel, fund administrators, and consultants. Returns firm names and service types.

        Parameters
        ----------
        id : str
            Investor name (e.g., 'Sequoia Capital') or entity ID from /investors/search

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvestorsServiceProvidersResponse
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.investors.service_providers(
                id="deal_openai_0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.service_providers(id, request_options=request_options)
        return _response.data

    async def service_providers_deal(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> InvestorsServiceProvidersDealResponse:
        """
        Get service providers involved in the investor's deal flow including transaction advisors and due diligence firms. Returns provider details specific to deal execution.

        Parameters
        ----------
        id : str
            Investor name (e.g., 'Sequoia Capital') or entity ID from /investors/search

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvestorsServiceProvidersDealResponse
            Successful response

        Examples
        --------
        import asyncio

        from runcaptain import AsyncCaptain

        client = AsyncCaptain(
            organization_id="YOUR_ORGANIZATION_ID",
            key="YOUR_KEY",
        )


        async def main() -> None:
            await client.investors.service_providers_deal(
                id="deal_openai_0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.service_providers_deal(id, request_options=request_options)
        return _response.data
